build:
  image: node:4
  commands:
    - npm install
    - npm test
    - npm run dist:gzip

publish:
  s3_sync:
    acl: public-read
    region: "eu-west-1"
    bucket: "living-styles.sandbox.aws.skyscnr.com"
    access_key: $$SANDBOX_ACCESS_KEY
    secret_key: $$SANDBOX_SECRET_KEY
    source: dist/
    target: /
    delete: true
    content_encoding:
      ".js": gzip
      ".css": gzip
      ".html": gzip
