name: Backpack CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set the correct npm version
        run: nvm install && nvm use

      - name: Install dependencies from npm
        run: |
          nvm use
          npm ci

      - name: Build Backpack
        run: |
          nvm use
          npm run build

      - name: Confirm the build hasn't changed any files
        run: ./scripts/check-pristine-state package-lock.json

      - name: Run tests
        run: npm test

      - name: Build Storybook
        if: github.ref == 'refs/heads/master'
        run: |
          nvm use
          npm run storybook:dist

      - name: Build Sass docs
        if: github.ref == 'refs/heads/master'
        run: |
          nvm use
          npm run sassdoc

      - name: Deploy Sass docs to backpack.github.io, if on master branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: dist-sassdoc/
          keep_files: true
          external_repository: backpack/sassdoc
          publish_branch: master

      - name: Deploy Storybook to backpack.github.io, if on master branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: dist-storybook/
          keep_files: true
          external_repository: backpack/storybook
          publish_branch: master
